version: "3.9"
services: 

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
  
  delivery:
    build: ./services/delivery
    container_name: delivery
    volumes:
      - ./services/delivery:/app
    ports:
      - 8080:3000
    environment:      
      - PORT=3000
    depends_on:
      - mongo
    working_dir: /app
    command: sh -c "cd /app; npm install; npm run dev"
