version: "3.9"
services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  delivery:
    build: ./services/delivery
    container_name: delivery
    ports:
      - 8080:${PORT}
    environment:      
      - PORT=${PORT}
      - COUNTER_URL=http://counter:3001
    depends_on:
      - counter
    command: sh -c "cd /app; rm -rf node_modules; npm install; npm run start"
