version: "3.9"
services: 

  delivery-front:
    build: ./services/delivery-front
    container_name: delivery-front
    volumes:
      - ./services/delivery-front:/app
    ports:
      - 8080:8080
    environment:      
      - PORT=3000
      - NODE_ENV=dev
    working_dir: /app
    command: sh -c "cd /app; npm install; npm run dev"
